# Generated by Django 3.2.2 on 2021-07-09 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mysource', models.CharField(max_length=225, verbose_name='栏目名称')),
                ('note', models.CharField(max_length=225, verbose_name='备注')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '链接分类',
                'verbose_name_plural': '链接分类',
            },
        ),
        migrations.CreateModel(
            name='My_source_setail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='链接名称')),
                ('link_address', models.CharField(max_length=225, verbose_name='链接地址')),
                ('note', models.CharField(max_length=225, verbose_name='备注')),
                ('mysource_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysource.my_source', verbose_name='关联分类')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
            },
        ),
    ]
