# Generated by Django 3.2.2 on 2021-07-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_source',
            name='note',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='my_source_setail',
            name='note',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='备注'),
        ),
    ]
