# Generated by Django 3.2.2 on 2021-07-10 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysource', '0002_auto_20210709_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_source_setail',
            new_name='My_source_detail',
        ),
    ]
