# Generated by Django 3.2.2 on 2021-07-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-created',), 'verbose_name': '文章', 'verbose_name_plural': '文章管理'},
        ),
    ]
