# Generated by Django 3.2.2 on 2021-07-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.CharField(default='匿名', max_length=30, verbose_name='未登录用户'),
        ),
    ]
