# Generated by Django 3.2.2 on 2021-07-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_comment_commenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
