# Generated by Django 3.2.2 on 2021-07-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
