# Generated by Django 3.2.2 on 2021-09-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_remove_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatar/%Y%m%d/'),
        ),
    ]
